Tiko/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('TikoEnergy.urls'))

]

TikoEnergy/urls.py
from django.conf.urls import url
from TikoEnergy import views

app_name = 'TikoEnergy'

urlpatterns = [
    url(r'^$', views.welcome, name='welcome'),
    url(r'^graph/$', views.graph, name='graph'),
    url(r'^user-register/$', views.register, name='register'),
    url(r'^user-login/$', views.user_login, name='login'),
    url(r'^user-logout/$', views.user_logout, name='logout'),
]

TikoEnergy/models.py
from django.contrib.auth.models import User

TikoEnergy/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email')

TikoEnergy/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from TikoEnergy.forms import UserForm


@login_required()
def welcome(request):
    context = {
    }
    return render(request, 'index.html', context)

@login_required()
def graph(request):
    context = {
    }
    return render(request, 'graph.html', context)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('TikoEnergy:welcome'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
    else:
        user_form = UserForm()
    return render(request, 'registration.html',
                  {'user_form': user_form,
                   'registered': registered})


def user_login(request):
    context = {
        'err_msg': None
    }
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('TikoEnergy:welcome'))
            else:
                context['err_msg'] = "Your account is not active."
                return render(request, 'login.html', {context})
        else:
            context['err_msg'] = "Invalid login details"
            return render(request, 'login.html', context)
    else:
        return render(request, 'login.html', context)

templates/base_index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>TIKO</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

    <script src="{% static 'js/bootstrap.js' %}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.3.0/Chart.min.js"></script>
    <script src="{% static 'js/live_graph.js' %}"></script>
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'TikoEnergy:welcome' %}">TIKO</a></li>
          {% if user.is_superuser %}
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          {% endif %}
          {% if user.is_authenticated %}
            <li><a href="{% url 'TikoEnergy:logout' %}">Logout</a></li>
          {% else %}
              <li><a class="navbar-link" href="{% url 'TikoEnergy:register' %}">Register</a></li>
              <li><a class="navbar-link" href="{% url 'TikoEnergy:login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/graph.html
{% extends "base_index.html" %}

{% block body_block %}
  <div class="jumbotron" >
    <h2>Graph page</h2>
    <div>
      <canvas id="myGraph"></canvas>
    </div>
  </div>

    <script>
        window.onload = function() {
          loadChart();
        };
    </script>
{% endblock %}

templates/index.html
{% extends "base_index.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Tiko Energy</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        <a class="btn btn-primary" href="/graph" role="button">Graph page</a>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
{% endblock %}

templates/login.html
{% extends 'base_index.html' %}
{% block body_block %}
    <div class="jumbotron">
      <h1>Login here :</h1>
        {% if err_msg %}
            <div class="alert alert-danger">
                <strong>Error</strong> {{ err_msg }}
            </div>
        {% endif %}
<form method="post" action="{% url 'TikoEnergy:login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
{% endblock %}

templates/registration.html
{% extends "base_index.html" %}
{% load staticfiles %}
{% block body_block %}
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register</h1>
        <h3>Fill out the form please</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
{% endblock %}